# Generated by Django 2.2 on 2019-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.IntegerField(default=1),
        ),
    ]
